apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-redis
  namespace: memegram
  labels:
    app: messaging-redis
    app.kubernetes.io/part-of: memegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-redis
  template:
    metadata:
      labels:
        app: messaging-redis
        app.kubernetes.io/part-of: memegram
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-redis
  namespace: memegram
  labels:
    app: messaging-redis
    app.kubernetes.io/part-of: memegram
spec:
  type: ClusterIP
  selector:
    app: messaging-redis
  ports:
    - port: 6379
      targetPort: 6379
